--------------------------------------------------------
--  Constraints for Table ANGAJAT
--------------------------------------------------------

  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_UK1" UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_CHK3" CHECK (bonus>=0) ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_CHK1" CHECK (id>0) ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("ORA_PLECARE" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("ORA_VENIRE" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("NUME" NOT NULL ENABLE);
