--------------------------------------------------------
--  Ref Constraints for Table ANGAJAT_FUNCTIE
--------------------------------------------------------

  ALTER TABLE "PROIECT"."ANGAJAT_FUNCTIE" ADD CONSTRAINT "CONEXIUNE_ANGAJAT_FUNCTIE_FK1" FOREIGN KEY ("ID_ANGAJAT")
	  REFERENCES "PROIECT"."ANGAJAT" ("ID") ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT_FUNCTIE" ADD CONSTRAINT "CONEXIUNE_ANGAJAT_FUNCTIE_FK2" FOREIGN KEY ("ID_FUNCTIE")
	  REFERENCES "PROIECT"."FUNCTIE" ("ID") ENABLE;
