--------------------------------------------------------
--  DDL for Table ANGAJAT
--------------------------------------------------------

  CREATE TABLE "PROIECT"."ANGAJAT" 
   (	"NUME" VARCHAR2(100 BYTE), 
	"PRENUME" VARCHAR2(100 BYTE), 
	"MAIL" VARCHAR2(100 BYTE), 
	"ID" NUMBER(*,0), 
	"ORA_VENIRE" NUMBER, 
	"ORA_PLECARE" NUMBER, 
	"BONUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
