--------------------------------------------------------
--  DDL for Materialized View ANGAJAT_COMPLET
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "PROIECT"."ANGAJAT_COMPLET" ("NUME", "PRENUME", "MAIL", "BONUS", "ID_ANGAJAT", "NUME_FUNCTIE", "SALAR", "NUME_MAGAZIN", "LOCATIE_MAGAZIN")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT angajat.nume,angajat.prenume,angajat.mail,angajat.bonus,angajat.id id_angajat,functie.NUME nume_functie,functie.salar,magazin.NUME nume_magazin,magazin.LOCATIE locatie_magazin FROM ANGAJAT JOIN ANGAJATi_magazin ON angajat.ID=ANGAJATi_magazin.ID_ANGAJAT 
JOIN ANGAJAT_FUNCTIE ON angajat.ID=ANGAJAT_FUNCTIE.ID_ANGAJAT 
JOIN functie ON angajat_functie.id_functie=functie.ID 
join magazin on angajati_magazin.id_magazin=magazin.ID;

   COMMENT ON MATERIALIZED VIEW "PROIECT"."ANGAJAT_COMPLET"  IS 'snapshot table for snapshot PROIECT.ANGAJAT_COMPLET';
