--------------------------------------------------------
--  Constraints for Table CATEGORII
--------------------------------------------------------

  ALTER TABLE "PROIECT"."CATEGORII" ADD CONSTRAINT "CATEGORII_CHK1" CHECK (ID>0) ENABLE;
  ALTER TABLE "PROIECT"."CATEGORII" ADD CONSTRAINT "CATEGORII_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."CATEGORII" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."CATEGORII" MODIFY ("NUME" NOT NULL ENABLE);
