--------------------------------------------------------
--  Ref Constraints for Table CATEGORII_PRODUSE
--------------------------------------------------------

  ALTER TABLE "PROIECT"."CATEGORII_PRODUSE" ADD CONSTRAINT "CONEXIUNE_CATEGORII_PRODU_FK1" FOREIGN KEY ("ID_CATEGORIE")
	  REFERENCES "PROIECT"."CATEGORII" ("ID") ENABLE;
  ALTER TABLE "PROIECT"."CATEGORII_PRODUSE" ADD CONSTRAINT "CONEXIUNE_CATEGORII_PRODU_FK2" FOREIGN KEY ("ID_PRODUS")
	  REFERENCES "PROIECT"."PRODUSE" ("ID") ENABLE;
