--------------------------------------------------------
--  Constraints for Table COMENZI
--------------------------------------------------------

  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_CHK1" CHECK (id>0) ENABLE;
  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ADRESS" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("DATA_LIVRARE" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ID_ANGAJAT" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ID_PRODUS" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("DATA_COMENZII" NOT NULL ENABLE);
