--------------------------------------------------------
--  Ref Constraints for Table COMENZI
--------------------------------------------------------

  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_FK1" FOREIGN KEY ("ID")
	  REFERENCES "PROIECT"."PRODUSE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_FK2" FOREIGN KEY ("ID")
	  REFERENCES "PROIECT"."USERS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_FK3" FOREIGN KEY ("ID_ANGAJAT")
	  REFERENCES "PROIECT"."ANGAJAT" ("ID") ON DELETE SET NULL ENABLE;
