--------------------------------------------------------
--  Constraints for Table FUNCTIE
--------------------------------------------------------

  ALTER TABLE "PROIECT"."FUNCTIE" ADD CONSTRAINT "FUNCTIE_CHK3" CHECK (SALAR>0) ENABLE;
  ALTER TABLE "PROIECT"."FUNCTIE" ADD CONSTRAINT "FUNCTIE_CHK2" CHECK (ID>0) ENABLE;
  ALTER TABLE "PROIECT"."FUNCTIE" ADD CONSTRAINT "FUNCTIE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."FUNCTIE" MODIFY ("SALAR" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."FUNCTIE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."FUNCTIE" MODIFY ("NUME" NOT NULL ENABLE);
