REM INSERTING into PROIECT.MAGAZIN
SET DEFINE OFF;
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Welch-Wilderman','1','8 Kropf Point');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Block and Sons','2','409 Artisan Street');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Wiegand-Daugherty','3','264 Claremont Avenue');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Hodkiewicz-Ortiz','4','30 Trailsway Trail');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Witting-Feeney','5','3 Merchant Hill');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Sipes-Gerhold','6','6096 Tennessee Drive');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Hodkiewicz and Sons','7','7 Parkside Alley');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Yundt, Orn and Borer','8','359 Fulton Hill');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Quitzon LLC','9','98971 Little Fleur Drive');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Heaney, Parisian and Huels','10','1596 Roxbury Street');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Miller, Weissnat and Klocko','11','195 Schmedeman Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Bergnaum and Sons','12','0717 High Crossing Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Mante Inc','13','51 Dwight Point');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Langworth-Kerluke','14','892 Atwood Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Lesch, Schowalter and Rohan','15','4807 Westend Junction');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Mueller-Murray','16','7955 Melvin Alley');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Kunze-Olson','17','9 Helena Alley');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Cassin, Hickle and McCullough','18','293 Quincy Center');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Crist-Wyman','19','077 Fisk Pass');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Hintz-Schultz','20','6 Waywood Plaza');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Predovic, Wilkinson and Luettgen','21','100 Arapahoe Crossing');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Watsica, Jaskolski and Medhurst','22','08777 Pleasure Lane');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Schowalter Group','23','86 Bowman Lane');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Bailey Group','24','1809 Alpine Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Bartoletti-Breitenberg','25','9 Almo Way');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Torp-Donnelly','26','32067 Ridgeway Court');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Mraz-Gleichner','27','0 Hovde Hill');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Wunsch LLC','28','2 Delaware Plaza');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Langworth, Thompson and Johnson','29','83897 Warbler Way');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Beier-Fritsch','30','21 Donald Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Beatty LLC','31','340 Banding Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Koepp Group','32','4642 Schiller Street');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Johns-Stark','33','5451 Ryan Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Kertzmann Group','34','0 Tennyson Pass');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Tremblay Group','35','18533 Barnett Lane');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Dietrich-Jacobs','36','3280 Loeprich Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Ullrich, Bailey and Harris','37','34 Sauthoff Circle');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Witting-Rosenbaum','38','6 Ridgeway Place');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Jones, Bernier and Pagac','39','8984 Harbort Center');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Reinger-Flatley','40','63 Quincy Lane');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('McCullough, Breitenberg and Considine','41','043 Brickson Park Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Doyle Group','42','938 Del Mar Park');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Wisozk LLC','43','52 Golf Course Drive');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Kreiger, Roob and Ryan','44','658 Maywood Plaza');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Grant and Sons','45','44304 Rutledge Way');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Conroy, Donnelly and Harvey','46','6089 American Point');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Kuhn, Kub and Bins','47','82 Leroy Hill');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Dicki-Erdman','48','81 Forest Avenue');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Casper, Wehner and Ledner','49','86 Prairie Rose Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Rogahn, Brekke and Nicolas','50','9646 Bunker Hill Court');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Bashirian, Rodriguez and DuBuque','51','2585 5th Way');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Pfeffer-Medhurst','52','3440 Westridge Place');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Gislason Group','53','433 Mendota Park');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Huels, Lind and Rau','54','49 Anderson Terrace');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Beatty-Ankunding','55','40 Sunnyside Way');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Blanda LLC','56','7 Jenifer Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Hettinger, Nolan and Wiza','57','41 Messerschmidt Point');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Harber, McDermott and Jacobi','58','72801 Hazelcrest Park');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Collier-Rohan','59','4 Michigan Court');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Howell LLC','60','22 Sycamore Plaza');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Stracke, Kiehn and Hickle','61','0 Katie Lane');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Mayer, O''Keefe and Fadel','62','16 Hovde Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Nikolaus-Monahan','63','1 Lerdahl Crossing');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Lind Inc','64','84981 Macpherson Center');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Larson, Lind and Kilback','65','256 Heffernan Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Schimmel Inc','66','6705 Coleman Drive');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Bogisich, King and Leannon','67','7 North Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Block-Goodwin','68','85 Badeau Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Heidenreich-Cronin','69','7550 Debs Junction');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Veum-Strosin','70','1 Johnson Trail');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Krajcik, Kuhic and Rolfson','71','1611 Northview Avenue');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Volkman, Wilkinson and Fay','72','1 Golf View Terrace');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Schowalter and Sons','73','7340 Lunder Pass');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Cummings-Upton','74','89 3rd Alley');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Morissette Group','75','29142 Sage Center');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Dare-Ritchie','76','153 Oakridge Hill');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Mayer-Waelchi','77','86 Victoria Crossing');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Kihn and Sons','78','2 Di Loreto Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Orn, Robel and Schumm','79','58 Leroy Hill');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Bartell-Bartoletti','80','8309 Clemons Pass');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Conn Group','81','9 Merchant Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Volkman Inc','82','758 Clemons Street');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Corkery, Daniel and Huels','83','2658 8th Court');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Gerlach, Aufderhar and Labadie','84','6007 Old Shore Pass');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Cormier and Sons','85','4498 North Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Wolf-Cremin','86','60632 Northport Pass');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Durgan and Sons','87','850 Comanche Park');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Boyle-Wunsch','88','90997 Shopko Avenue');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Witting-Brakus','89','44 Buhler Trail');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Walter-Howe','90','16 Melrose Street');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Thiel, Bosco and Kirlin','91','243 Transport Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Windler-Effertz','92','57 Acker Alley');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Ryan-Connelly','93','17 Novick Center');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Williamson LLC','94','10 Dunning Avenue');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Ward-Mayert','95','2605 Londonderry Parkway');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Greenfelder, Eichmann and Friesen','96','914 Division Park');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Kihn-Hamill','97','926 Corscot Hill');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Krajcik Inc','98','39 Packers Center');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Marvin, Bayer and Streich','99','33 Morningstar Road');
Insert into PROIECT.MAGAZIN (NUME,ID,LOCATIE) values ('Grady-Schuppe','100','85 Scoville Point');
