--------------------------------------------------------
--  Constraints for Table PRODUSE
--------------------------------------------------------

  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK5" CHECK (NUMBEROF>=0.0) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK2" CHECK (PRET>0.0) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK1" CHECK (ID>0.0) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK4" CHECK (OFERTA >=0) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK3" CHECK (RATING >=0 and rating <=10) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("NUMBEROF" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("PRET" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("NUME" NOT NULL ENABLE);
