--------------------------------------------------------
--  DDL for Materialized View PRODUSE_MV
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "PROIECT"."PRODUSE_MV" ("NUME", "ID", "PRET", "RATING", "OFERTA", "NUMBEROF")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  REFRESH FORCE ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS FOR UPDATE DISABLE QUERY REWRITE
  AS SELECT "PRODUSE"."NUME" "NUME","PRODUSE"."ID" "ID","PRODUSE"."PRET" "PRET","PRODUSE"."RATING" "RATING","PRODUSE"."OFERTA" "OFERTA","PRODUSE"."NUMBEROF" "NUMBEROF" FROM "PRODUSE" "PRODUSE";

   COMMENT ON MATERIALIZED VIEW "PROIECT"."PRODUSE_MV"  IS 'snapshot table for snapshot PROIECT.PRODUSE_MV';
