--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PROIECT"."USERS" ADD CONSTRAINT "USERS_CHK2" CHECK (id>0) ENABLE;
  ALTER TABLE "PROIECT"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("ID", "MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."USERS" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."USERS" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."USERS" MODIFY ("NUME" NOT NULL ENABLE);
