--------------------------------------------------------
--  DDL for Table USLOG$_PRODUSE_MV
--------------------------------------------------------

  CREATE TABLE "PROIECT"."USLOG$_PRODUSE_MV" 
   (	"ID" NUMBER, 
	"SNAPTIME$$" DATE, 
	"DMLTYPE$$" VARCHAR2(1 BYTE), 
	"OLD_NEW$$" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "PROIECT"."USLOG$_PRODUSE_MV"  IS 'log of updates to snapshot table PROIECT.PRODUSE_MV';
