--------------------------------------------------------
--  File created - vineri-martie-17-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANGAJAT
--------------------------------------------------------

  CREATE TABLE "PROIECT"."ANGAJAT" 
   (	"NUME" VARCHAR2(20 BYTE), 
	"PRENUME" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"ID" NUMBER(*,0), 
	"ORA_VENIRE" NUMBER, 
	"ORA_PLECARE" NUMBER, 
	"BONUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANGAJATI_MAGAZIN
--------------------------------------------------------

  CREATE TABLE "PROIECT"."ANGAJATI_MAGAZIN" 
   (	"ID_ANGAJAT" NUMBER(*,0), 
	"ID_MAGAZIN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIE_PREFERATA
--------------------------------------------------------

  CREATE TABLE "PROIECT"."CATEGORIE_PREFERATA" 
   (	"USER_ID" NUMBER(*,0), 
	"CATEGORY_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORII
--------------------------------------------------------

  CREATE TABLE "PROIECT"."CATEGORII" 
   (	"NUME" VARCHAR2(20 BYTE), 
	"ID" NUMBER(*,0), 
	"PRODUCT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMENZI
--------------------------------------------------------

  CREATE TABLE "PROIECT"."COMENZI" 
   (	"DATA_COMENZII" DATE, 
	"ID_PRODUS" NUMBER, 
	"ID_ANGAJAT" NUMBER, 
	"ID" NUMBER, 
	"DATA_LIVRARE" DATE, 
	"ADRESS" VARCHAR2(20 BYTE), 
	"ID_USER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FUNCTIE
--------------------------------------------------------

  CREATE TABLE "PROIECT"."FUNCTIE" 
   (	"NUME" VARCHAR2(20 BYTE), 
	"NIVEL" NUMBER, 
	"ID" NUMBER(*,0), 
	"ID_ANGAJAT" NUMBER(*,0), 
	"SALAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAGAZIN
--------------------------------------------------------

  CREATE TABLE "PROIECT"."MAGAZIN" 
   (	"NUME" VARCHAR2(20 BYTE), 
	"ID" NUMBER(*,0), 
	"LOCATIE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUSE
--------------------------------------------------------

  CREATE TABLE "PROIECT"."PRODUSE" 
   (	"NUME" VARCHAR2(20 BYTE), 
	"ID" NUMBER(*,0), 
	"PRET" NUMBER, 
	"RATING" NUMBER, 
	"OFERTA" NUMBER, 
	"NUMBEROF" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PROIECT"."USERS" 
   (	"NUME" VARCHAR2(30 BYTE), 
	"PRENUME" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"DATA_NASTERE" DATE, 
	"ADRESA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROIECT.ANGAJAT
SET DEFINE OFF;
REM INSERTING into PROIECT.ANGAJATI_MAGAZIN
SET DEFINE OFF;
REM INSERTING into PROIECT.CATEGORIE_PREFERATA
SET DEFINE OFF;
REM INSERTING into PROIECT.CATEGORII
SET DEFINE OFF;
REM INSERTING into PROIECT.COMENZI
SET DEFINE OFF;
REM INSERTING into PROIECT.FUNCTIE
SET DEFINE OFF;
REM INSERTING into PROIECT.MAGAZIN
SET DEFINE OFF;
REM INSERTING into PROIECT.PRODUSE
SET DEFINE OFF;
REM INSERTING into PROIECT.USERS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ANGAJAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROIECT"."ANGAJAT_PK" ON "PROIECT"."ANGAJAT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANGAJAT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROIECT"."ANGAJAT_UK1" ON "PROIECT"."ANGAJAT" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORII_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROIECT"."CATEGORII_PK" ON "PROIECT"."CATEGORII" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMENZI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROIECT"."COMENZI_PK" ON "PROIECT"."COMENZI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FUNCTIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROIECT"."FUNCTIE_PK" ON "PROIECT"."FUNCTIE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROIECT"."PRODUSE_PK" ON "PROIECT"."PRODUSE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROIECT"."TABLE1_PK" ON "PROIECT"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROIECT"."TABLE1_PK1" ON "PROIECT"."MAGAZIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROIECT"."TABLE1_UK1" ON "PROIECT"."USERS" ("ID", "MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANGAJAT
--------------------------------------------------------

  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_UK1" UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_CHK5" CHECK (ora_venire in (1,24)) ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_CHK4" CHECK (ora_plecare in (1,24)) ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_CHK3" CHECK (bonus>=0) ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_CHK2" CHECK (mail like '%@%\.%') ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_CHK1" CHECK (id>0) ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" ADD CONSTRAINT "ANGAJAT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("ORA_PLECARE" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("ORA_VENIRE" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJAT" MODIFY ("NUME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANGAJATI_MAGAZIN
--------------------------------------------------------

  ALTER TABLE "PROIECT"."ANGAJATI_MAGAZIN" MODIFY ("ID_MAGAZIN" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."ANGAJATI_MAGAZIN" MODIFY ("ID_ANGAJAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIE_PREFERATA
--------------------------------------------------------

  ALTER TABLE "PROIECT"."CATEGORIE_PREFERATA" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."CATEGORIE_PREFERATA" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORII
--------------------------------------------------------

  ALTER TABLE "PROIECT"."CATEGORII" ADD CONSTRAINT "CATEGORII_CHK1" CHECK (ID>0) ENABLE;
  ALTER TABLE "PROIECT"."CATEGORII" ADD CONSTRAINT "CATEGORII_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."CATEGORII" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."CATEGORII" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."CATEGORII" MODIFY ("NUME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMENZI
--------------------------------------------------------

  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_CHK1" CHECK (id>0) ENABLE;
  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ADRESS" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("DATA_LIVRARE" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ID_ANGAJAT" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("ID_PRODUS" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."COMENZI" MODIFY ("DATA_COMENZII" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FUNCTIE
--------------------------------------------------------

  ALTER TABLE "PROIECT"."FUNCTIE" ADD CONSTRAINT "FUNCTIE_CHK3" CHECK (SALAR>0) ENABLE;
  ALTER TABLE "PROIECT"."FUNCTIE" ADD CONSTRAINT "FUNCTIE_CHK2" CHECK (ID>0) ENABLE;
  ALTER TABLE "PROIECT"."FUNCTIE" ADD CONSTRAINT "FUNCTIE_CHK1" CHECK (NIVEL>0) ENABLE;
  ALTER TABLE "PROIECT"."FUNCTIE" ADD CONSTRAINT "FUNCTIE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."FUNCTIE" MODIFY ("SALAR" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."FUNCTIE" MODIFY ("ID_ANGAJAT" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."FUNCTIE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."FUNCTIE" MODIFY ("NIVEL" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."FUNCTIE" MODIFY ("NUME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAGAZIN
--------------------------------------------------------

  ALTER TABLE "PROIECT"."MAGAZIN" ADD CONSTRAINT "MAGAZIN_CHK1" CHECK (ID>0) ENABLE;
  ALTER TABLE "PROIECT"."MAGAZIN" ADD CONSTRAINT "MAGAZIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."MAGAZIN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."MAGAZIN" MODIFY ("NUME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUSE
--------------------------------------------------------

  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK5" CHECK (NUMBEROF>=0) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK4" CHECK (OFERTA >0) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK3" CHECK (RATING IN (0,10)) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK2" CHECK (PRET>0) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_CHK1" CHECK (ID>0) ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" ADD CONSTRAINT "PRODUSE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("NUMBEROF" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("PRET" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."PRODUSE" MODIFY ("NUME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PROIECT"."USERS" ADD CONSTRAINT "USERS_CHK2" CHECK (id>0) ENABLE;
  ALTER TABLE "PROIECT"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("ID", "MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."USERS" ADD CONSTRAINT "USERS_CHK1" CHECK (MAIL like '%@%\.%') ENABLE;
  ALTER TABLE "PROIECT"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROIECT"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."USERS" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."USERS" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "PROIECT"."USERS" MODIFY ("NUME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ANGAJATI_MAGAZIN
--------------------------------------------------------

  ALTER TABLE "PROIECT"."ANGAJATI_MAGAZIN" ADD CONSTRAINT "ANGAJATI_MAGAZIN_FK1" FOREIGN KEY ("ID_ANGAJAT")
	  REFERENCES "PROIECT"."ANGAJAT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROIECT"."ANGAJATI_MAGAZIN" ADD CONSTRAINT "ANGAJATI_MAGAZIN_FK2" FOREIGN KEY ("ID_ANGAJAT")
	  REFERENCES "PROIECT"."MAGAZIN" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORIE_PREFERATA
--------------------------------------------------------

  ALTER TABLE "PROIECT"."CATEGORIE_PREFERATA" ADD CONSTRAINT "CATEGORIE_PREFERATA_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "PROIECT"."USERS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROIECT"."CATEGORIE_PREFERATA" ADD CONSTRAINT "CATEGORIE_PREFERATA_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "PROIECT"."CATEGORII" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORII
--------------------------------------------------------

  ALTER TABLE "PROIECT"."CATEGORII" ADD CONSTRAINT "CATEGORII_FK1" FOREIGN KEY ("ID")
	  REFERENCES "PROIECT"."PRODUSE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMENZI
--------------------------------------------------------

  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_FK1" FOREIGN KEY ("ID")
	  REFERENCES "PROIECT"."PRODUSE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_FK2" FOREIGN KEY ("ID")
	  REFERENCES "PROIECT"."USERS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROIECT"."COMENZI" ADD CONSTRAINT "COMENZI_FK3" FOREIGN KEY ("ID")
	  REFERENCES "PROIECT"."ANGAJAT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FUNCTIE
--------------------------------------------------------

  ALTER TABLE "PROIECT"."FUNCTIE" ADD CONSTRAINT "FUNCTIE_FK1" FOREIGN KEY ("ID")
	  REFERENCES "PROIECT"."ANGAJAT" ("ID") ON DELETE CASCADE ENABLE;
