set SERVEROUTPUT ON;
declare 
cursor cursor_1 is SELECT USERS.NAME,COUNT(QUESTIONS.REPORT_RESOLVED) FROM USERS JOIN QUESTIONS ON USERS.ID=QUESTIONS.USER_ID WHERE TRUNC(QUESTIONS.UPDATED_AT) >=TO_DATE('15-01-2017','DD MM YYYY') AND QUESTIONS.REPORTED>=5
group by users.name;
counter NUMBER:=0;
BEGIN
UPDATE QUESTIONS SET REPORT_RESOLVED =2 WHERE TRUNC(UPDATED_AT) >=TO_DATE('15-01-2017','DD MM YYYY') AND REPORTED>=5;
FOR linie_cursor in cursor_1 LOOP
  dbms_output.put_line(linie_cursor.NAME);
END LOOP;
sys.DBMS_OUTPUT.PUT_LINE(counter);
END;
    